# Generated by Django 5.1.6 on 2025-02-13 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Students",
        ),
    ]
