# Generated by Django 5.1.6 on 2025-02-24 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hire_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
