# Generated by Django 5.1.6 on 2025-02-25 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
